# syntax=docker/dockerfile:1
FROM --platform=$BUILDPLATFORM maven:3-eclipse-temurin-25 AS build
WORKDIR /src
COPY pom.xml ./
RUN mvn -q -B dependency:go-offline
COPY src ./src
RUN mvn -q -B package && mkdir -p /out && cp target/app.jar /out/app.jar

FROM scratch
COPY --from=build /out /app
