services:
  web:
    image: wyga/web-runtime-dotnet:latest
    ports:
      - "8000:8080"
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      update_config:
        order: start-first
