<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>dotnet</AssemblyName>
    <RootNamespace>App</RootNamespace>
    <DebugType>none</DebugType>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <IsTransformWebConfigDisabled>true</IsTransformWebConfigDisabled>
  </PropertyGroup>
</Project>
