services:
  web:
    image: wyga/web-runtime-java:latest
    environment:
      - RUNTIME_NODE={{.Node.Hostname}}
      - RUNTIME_NODE_ID={{.Node.ID}}
      - RUNTIME_TASK={{.Task.Name}}
      - RUNTIME_SLOT={{.Task.Slot}}
    ports:
      - "8021:8080"
    deploy:
      replicas: 4
      placement:
        constraints:
          - node.labels.OS == LINUX
      restart_policy:
        condition: any
      update_config:
        order: start-first
